[project]
name = "pyipx800v3"
description = "lib to interact with IPX800v3"
version = "0.1.0"
authors = [
    { name = "Xavier ROQUES", email = "xavier.roques@gmail.com" }
]
dependencies = [
    "requests"
]

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]